using System.Collections.Generic;

namespace Marten.Schema
{
    public interface IDbObjects
    {
        /// <summary>
        /// Fetches a list of all of the Marten generated tables
        /// in the database
        /// </summary>
        /// <returns></returns>
        TableName[] SchemaTables();

        /// <summary>
        /// Fetches a list of the Marten document tables
        /// in the database
        /// </summary>
        /// <returns></returns>
        TableName[] DocumentTables();

        /// <summary>
        /// Fetches a list of functions generated by Marten
        /// in the database
        /// </summary>
        /// <returns></returns>
        FunctionName[] SchemaFunctionNames();

        bool TableExists(TableName table);


        IEnumerable<IndexDef> IndexesFor(TableName table);

    }

    public class IndexDef
    {
        public string Name { get; }
        public string DDL { get; }

        public IndexDef(string name, string ddl)
        {
            Name = name;
            DDL = ddl;
        }
    }
}