#nullable enable
using System;
using System.Reflection;
using JasperFx.Core.Reflection;
using Marten.Storage;

namespace Marten.Storage.Identification;

/// <summary>
/// W3 spike (M14): <see cref="IIdentification{TDoc, TId}"/> for
/// documents whose id is a <see cref="Guid"/> generated by
/// <c>Guid.NewGuid()</c> (random, non-sequential). Sibling of
/// <see cref="SequentialGuidIdentification{TDoc}"/>; differs only in the
/// generator used.
/// </summary>
public sealed class GuidIdentification<TDoc>: IIdentification<TDoc, Guid>
    where TDoc : notnull
{
    private readonly Func<TDoc, Guid> _getter;
    private readonly Action<TDoc, Guid> _setter;

    public GuidIdentification(MemberInfo idMember)
    {
        _getter = LambdaBuilder.Getter<TDoc, Guid>(idMember);
        _setter = LambdaBuilder.Setter<TDoc, Guid>(idMember)!;
    }

    public Guid Identity(TDoc document) => _getter(document);

    public Guid AssignIfMissing(TDoc document, IMartenDatabase database)
    {
        var current = _getter(document);
        if (current != Guid.Empty)
        {
            return current;
        }

        var assigned = Guid.NewGuid();
        _setter(document, assigned);
        return assigned;
    }
}
