using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Newtonsoft.Json;

namespace DinnerParty.Models
{
    public class Dinner
    {
        /// <summary>
        /// This is the unique numeric id for each dinner
        /// </summary>
        /// <remarks>
        /// This property is automatically generated by marten's HiLo key algorithm
        /// See: https://github.com/JasperFx/marten/blob/master/documentation/documentation/documents/document_ids.md#hilo-sequences
        /// </remarks>
        public int Id { get; set; }

        /// <summary>
        /// This property is a shortcut to creating the REST url for this dinner
        /// </summary>
        [JsonIgnore]
        public string DinnerID => $"dinners/{Id}";

        [Required(ErrorMessage = "Title is required")]
        [StringLength(50, ErrorMessage = "Title may not be longer than 50 characters")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Event Date is required")]
        [Display(Name = "Event Date")]
        public DateTime EventDate { get; set; }

        [Required(ErrorMessage = "Description is required")]
        [StringLength(256, ErrorMessage = "Description may not be longer than 256 characters")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [StringLength(20, ErrorMessage = "Hosted By name may not be longer than 20 characters")]
        [Display(Name = "Host's Name")]
        public string HostedBy { get; set; }

        [Required(ErrorMessage = "Contact info is required")]
        [StringLength(20, ErrorMessage = "Contact info may not be longer than 20 characters")]
        [Display(Name = "Contact Info")]
        public string ContactPhone { get; set; }

        [Required(ErrorMessage = "Address is required")]
        [StringLength(50, ErrorMessage = "Address may not be longer than 50 characters")]
        [Display(Name = "Address, City, State, ZIP")]
        public string Address { get; set; }

        [UIHint("CountryDropDown")]
        public string Country { get; set; }

        public double Latitude { get; set; }

        public double Longitude { get; set; }

        public string HostedById { get; set; }

        public virtual ICollection<RSVP> RSVPs { get; set; }

        public bool IsHostedBy(string userName)
        {
            return String.Equals(HostedById ?? HostedBy, userName, StringComparison.Ordinal);
        }

        public bool IsUserRegistered(string userName)
        {
            return RSVPs.Any(r => r.AttendeeNameId == userName || (r.AttendeeNameId == null && r.AttendeeName == userName));
        }

        [UIHint("LocationDetail")]
        [JsonIgnore]
        public LocationDetail Location
        {
            get
            {
                return new LocationDetail() { Latitude = Latitude, Longitude = Longitude, Title = Title, Address = Address };
            }
            set
            {
                Latitude = value.Latitude;
                Longitude = value.Longitude;
                Title = value.Title;
                Address = value.Address;
            }
        }

        public DateTime LastModified { get; set; }
    }

    public class LocationDetail
    {
        public double Latitude;
        public double Longitude;
        public string Title;
        public string Address;
    }
}