using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Marten.SourceGenerator;

/// <summary>
/// PoC source generator (#4405) — finds <c>ICompiledQuery&lt;TDoc, TOut&gt;</c> implementations
/// in assemblies marked with <c>[JasperFxAssembly]</c> and emits typed scaffolding so
/// Marten's runtime never invokes <c>JasperFx.RuntimeCompiler</c> for compiled queries.
/// </summary>
/// <remarks>
/// <para>
/// <b>Current state — PoC initialized.</b> This file is the build-pipeline-validation
/// commit. The generator emits a marker class per discovered compiled query type so we
/// can confirm:
/// </para>
/// <list type="bullet">
///   <item>The analyzer project compiles + packs as an analyzer-only NuGet payload.</item>
///   <item>The incremental-generator wiring fires when a consumer references the generator.</item>
///   <item>Symbol discovery picks up <c>ICompiledQuery&lt;,&gt;</c> implementations in the
///         user's assembly when <c>[JasperFxAssembly]</c> is present.</item>
///   <item>Generated source appears in the consumer's <c>obj/Generated/</c> output.</item>
/// </list>
/// <para>
/// Real scaffolding emission (typed parameter binders, registry registration, scaffold
/// types) lands in subsequent commits per #4405's milestones.
/// </para>
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class CompiledQuerySourceGenerator : IIncrementalGenerator
{
    private const string ICompiledQueryMetadataName = "Marten.Linq.ICompiledQuery`2";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Step 1 — gate on [JasperFxAssembly] being present on the consumer assembly.
        // The assembly attribute is the source-gen scope marker per the master plan in
        // #4404; without it the generator emits nothing.
        var hasJasperFxAssembly = context.CompilationProvider.Select((compilation, _) =>
            compilation.Assembly.GetAttributes().Any(a =>
                a.AttributeClass?.ToDisplayString() == "JasperFx.JasperFxAssemblyAttribute"));

        // Step 2 — find every class that implements ICompiledQuery<,>.
        var compiledQueryTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax c && c.BaseList is not null,
                transform: static (ctx, ct) => TryGetCompiledQueryType(ctx, ct))
            .Where(static x => x is not null)
            .Select(static (x, _) => x!.Value);

        // Step 3 — emit one marker class per discovered query type. Real scaffolding
        // emission follows in subsequent PoC iterations (see file-level remarks).
        var combined = compiledQueryTypes.Combine(hasJasperFxAssembly);

        context.RegisterSourceOutput(combined, static (spc, pair) =>
        {
            var (queryType, gated) = pair;
            if (!gated) return;
            EmitMarker(spc, queryType);
        });
    }

    private static CompiledQueryTypeInfo? TryGetCompiledQueryType(GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.Node is not ClassDeclarationSyntax decl)
        {
            return null;
        }

        var symbol = ctx.SemanticModel.GetDeclaredSymbol(decl, ct) as INamedTypeSymbol;
        if (symbol is null || symbol.IsAbstract)
        {
            return null;
        }

        // Look for ICompiledQuery<TDoc, TOut> in the interface list.
        var iface = symbol.AllInterfaces.FirstOrDefault(i =>
            i.IsGenericType && i.ConstructedFrom.ToDisplayString() == "Marten.Linq.ICompiledQuery<TDoc, TOut>");

        if (iface is null)
        {
            return null;
        }

        return new CompiledQueryTypeInfo(
            FullName: symbol.ToDisplayString(),
            DocTypeFullName: iface.TypeArguments[0].ToDisplayString(),
            OutputTypeFullName: iface.TypeArguments[1].ToDisplayString(),
            SimpleName: symbol.Name,
            Namespace: symbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : symbol.ContainingNamespace.ToDisplayString());
    }

    private static void EmitMarker(SourceProductionContext spc, CompiledQueryTypeInfo info)
    {
        // PoC marker — proves the generator runs end-to-end. Subsequent commits replace
        // this with real scaffolding (typed parameter binder + scaffold type + registry
        // registration) per #4405.
        var hint = $"{info.SimpleName}_CompiledQueryMarker.g.cs";
        var nsBlock = info.Namespace is null
            ? string.Empty
            : $"namespace {info.Namespace};\n\n";

        var source = $$"""
            // <auto-generated/>
            // Marten.SourceGenerator PoC marker — #4405.
            // Discovered compiled query: {{info.FullName}}
            // Doc type: {{info.DocTypeFullName}}
            // Output type: {{info.OutputTypeFullName}}
            //
            // This marker class confirms the generator pipeline fires for this type. Real
            // scaffolding (typed parameter binder, runtime scaffold, registry registration)
            // lands in subsequent commits per the PoC milestones.

            #nullable enable

            {{nsBlock}}internal static class {{info.SimpleName}}_CompiledQueryMarker
            {
                public const string DiscoveredQueryFullName = "{{info.FullName}}";
                public const string DocTypeFullName = "{{info.DocTypeFullName}}";
                public const string OutputTypeFullName = "{{info.OutputTypeFullName}}";
            }
            """;

        spc.AddSource(hint, source);
    }

    private readonly record struct CompiledQueryTypeInfo(
        string FullName,
        string DocTypeFullName,
        string OutputTypeFullName,
        string SimpleName,
        string? Namespace);
}
