using System.Collections.Generic;
using System.Text;

namespace Marten.SourceGeneration;

/// <summary>
///     Emits the DiscoveredMartenTypes static manifest class containing
///     compile-time discovered document, projection, and event types.
/// </summary>
internal static class DiscoveredMartenTypesEmitter
{
    public static string Emit(
        List<string> documentTypes,
        List<string> projectionTypes,
        List<string> eventTypes)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// This file is generated by Marten.SourceGeneration.");
        sb.AppendLine("// Do not edit manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace Marten.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("///     Compile-time discovered Marten types. Used by StoreOptions to bypass");
        sb.AppendLine("///     runtime assembly scanning when source generation is opted into.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class DiscoveredMartenTypes");
        sb.AppendLine("{");

        // Document types
        EmitTypeArray(sb, "DocumentTypes", documentTypes);
        sb.AppendLine();

        // Projection types
        EmitTypeArray(sb, "ProjectionTypes", projectionTypes);
        sb.AppendLine();

        // Event types
        EmitTypeArray(sb, "EventTypes", eventTypes);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitTypeArray(StringBuilder sb, string propertyName, List<string> types)
    {
        sb.AppendLine($"    public static IReadOnlyList<Type> {propertyName} => new Type[]");
        sb.AppendLine("    {");

        foreach (var type in types)
        {
            sb.AppendLine($"        typeof({type}),");
        }

        sb.AppendLine("    };");
    }
}
